import { describe, expect, test } from "bun:test";
import type { FitMeasure } from "@auteur/core/fit";
import type { ExportInput } from "./render-export.ts";
import { attributionFor, renderExport } from "./render-export.ts";

const measure = (overrides: Partial<FitMeasure> = {}): FitMeasure => ({
  band: [9, 11.2],
  bandBasis: "iqr",
  corpusValue: 11.2,
  label: "semicolons per 1k",
  path: "prosody.punctuation.semicolon",
  status: "drift",
  targetOrigin: "measured",
  targetValue: 11.2,
  value: 6.1,
  ...overrides,
});

const input = (overrides: Partial<ExportInput> = {}): ExportInput => ({
  author: { displayName: "Jorge Luis Borges" },
  cardVersion: 3,
  confidence: 0.86,
  decisions: [
    {
      decision: "the catalogue frame",
      origin: "you answered",
      reason: "you picked it in round 1",
    },
    {
      decision: "the narrator is at a distance",
      origin: "model chose — not asked",
      reason: "no question covered narrator distance",
    },
  ],
  markdown: "The lamp turned. The sea did not.",
  measures: [measure()],
  summary: "Four of five measures inside the corpus band.",
  title: "The Return of the Comet",
  wordCount: 1042,
  ...overrides,
});

const LABEL = { authorName: "Jorge Luis Borges" };

describe("the label is required and cannot be forgotten", () => {
  test("the call does not compile without it", () => {
    // §7.6's rule as a type rather than a convention: making it a caller's
    // responsibility means one day a caller forgets — not through
    // carelessness, but because the call site that forgets is the one added
    // last by someone who read the other three and assumed.
    // @ts-expect-error the label is required
    const missing = () => renderExport(input());
    expect(typeof missing).toBe("function");
  });

  test("an empty string cannot stand in for a label", () => {
    // A `string` parameter would be satisfied by "", and an empty label
    // type-checks its way to a document with the required sentence missing.
    // @ts-expect-error the label is an object naming the author, not a string
    const wrong = () => renderExport(input(), "");
    expect(typeof wrong).toBe("function");
  });

  test("the rendered document carries the §7.6 sentence verbatim", () => {
    const document = renderExport(input(), LABEL);
    expect(document).toContain(
      "Generated by auteur in the style of Jorge Luis Borges.",
    );
    expect(document).toContain("AI-generated text; not written by the author.");
  });

  test("the sentence names the author the label names", () => {
    expect(attributionFor({ authorName: "Anton Chekhov" })).toContain(
      "Anton Chekhov",
    );
  });
});

describe("what travels with the story", () => {
  const document = renderExport(input(), LABEL);

  test("the prose comes first, under its title", () => {
    expect(document.indexOf("# The Return of the Comet")).toBeLessThan(
      document.indexOf("The lamp turned."),
    );
  });

  test("the author and the card version", () => {
    // So a reader who did not run the session can tell which card produced it,
    // and go and read that card.
    expect(document).toContain("card@3, confidence 0.86");
    expect(document).toContain("1,042 words");
  });

  test("the style-fit summary and the measures", () => {
    expect(document).toContain("Four of five measures inside the corpus band.");
    expect(document).toContain("semicolons per 1k");
    expect(document).toContain("drift");
  });

  test("the decisions log, including what no question covered", () => {
    // The interesting entries are the ones the wizard never surfaced: a reader
    // meets them for the first time in the finished story.
    expect(document).toContain("model chose — not asked");
    expect(document).toContain("no question covered narrator distance");
  });

  test("the label sits before the rest of the trailing matter", () => {
    // It is the one part a reader who scrolls past everything else must still
    // meet.
    expect(document.indexOf("Generated by auteur")).toBeLessThan(
      document.indexOf("card@3"),
    );
  });
});

describe("the units follow what is measured", () => {
  test("a punctuation rate renders per thousand words", () => {
    // Derived from the path rather than carried on the measure: the unit is a
    // property of what is measured, and a `unit` field would be one the
    // extraction stage could get wrong.
    expect(renderExport(input(), LABEL)).toContain("/1k");
  });

  test("a ratio renders as a fraction, not as a word count", () => {
    const document = renderExport(
      input({
        measures: [
          measure({
            band: [0.44, 0.52],
            corpusValue: 0.48,
            label: "type-token ratio",
            path: "prosody.mattr",
            targetValue: 0.48,
            value: 0.46,
          }),
        ],
      }),
      LABEL,
    );
    expect(document).toContain("0.46");
    expect(document).not.toContain("0.46 w");
  });
});

describe("a proxy measure says so in the export too", () => {
  test("the classifier is named beside the value", () => {
    // A reader is never shown the verdict without being told what produced it,
    // and an exported document outlives the screen it was read on.
    const document = renderExport(
      input({
        measures: [
          measure({
            classifier: { kind: "suffix-proxy", validated: false },
            label: "latinate ratio",
            path: "prosody.latinateRatio",
          }),
        ],
      }),
      LABEL,
    );
    expect(document).toContain("suffix proxy, unvalidated");
  });
});

describe("the empty cases", () => {
  test("a story with no title renders without a heading", () => {
    const document = renderExport(input({ title: undefined }), LABEL);
    expect(document.startsWith("The lamp turned.")).toBe(true);
  });

  test("no decisions says so rather than leaving a blank section", () => {
    // A blank section reads as a bug; a sentence reads as a fact.
    expect(renderExport(input({ decisions: [] }), LABEL)).toContain(
      "Nothing was decided that no question covered.",
    );
  });

  test("no measures renders the summary and no table", () => {
    const document = renderExport(input({ measures: [] }), LABEL);
    expect(document).not.toContain("| measure |");
    expect(document).toContain("Four of five measures");
  });
});
