#!/usr/bin/env bun
/**
 * Inline every `sql/NNNN_*.sql` into `src/generated/manifest.ts`.
 *
 * **Inlined rather than read from disk at run time.** A bundled serverless
 * function does not ship arbitrary files, so a runtime `readdir` finds zero
 * migrations and `ensureSchema()` cheerfully reports the database up to date —
 * which is the worst failure this package has, and the one nexus actually
 * shipped. A generated module is part of the bundle by construction.
 *
 * The checksum is over the file's bytes. It is verified on every boot, so an
 * edit to an applied migration aborts rather than diverging the recorded state
 * from the real schema.
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const SQL_DIR = join(ROOT, "sql");

const files = (await readdir(SQL_DIR))
  .filter((name) => name.endsWith(".sql"))
  .sort();

const entries: string[] = [];
for (const file of files) {
  const match = /^(\d{4})_(.+)\.sql$/.exec(file);
  if (match?.[1] === undefined || match[2] === undefined) {
    throw new Error(
      `${file} is not named NNNN_name.sql, so its order in the ledger is undefined.`,
    );
  }
  const sql = await Bun.file(join(SQL_DIR, file)).text();
  const checksum = Bun.hash(sql).toString(16).padStart(16, "0");
  entries.push(
    [
      "  {",
      `    checksum: ${JSON.stringify(checksum)},`,
      `    name: ${JSON.stringify(match[2])},`,
      `    sql: ${JSON.stringify(sql)},`,
      `    version: ${Number.parseInt(match[1], 10).toString()},`,
      "  },",
    ].join("\n"),
  );
}

const generated = [
  "// Generated by `bun run build` in @auteur/migrations. Do not edit.",
  "//",
  "// Inlined rather than read from disk so a bundled function cannot find zero",
  "// migrations at run time and report the database up to date.",
  "",
  "export type Migration = {",
  "  readonly version: number;",
  "  readonly name: string;",
  "  readonly sql: string;",
  "  readonly checksum: string;",
  "};",
  "",
  "export const MIGRATIONS: readonly Migration[] = [",
  ...entries,
  "];",
  "",
].join("\n");

await Bun.write(join(ROOT, "src", "generated", "manifest.ts"), generated);
process.stdout.write(`inlined ${files.length.toString()} migration(s)\n`);
