// Placeholder generated by `bun run new:package`. The work package that owns
// this module replaces it with the real implementation of `ensure-schema`.

export const unimplemented = (): never => {
  throw new Error("unimplemented: ensure-schema");
};
