import { afterEach, describe, expect, test } from "bun:test";
import { COPY } from "@auteur/copy/index";
import { AuteurError } from "@auteur/errors/auteur-error";
import { renderStyled } from "@auteur/test-support/render";
import { act } from "react";
import { demoState, demoTransport } from "../demo/transport.ts";
import { App } from "../shell/app.tsx";
import type { Transport } from "../shell/session-state.ts";

/**
 * The finished story leaving the screen.
 *
 * The export route and its renderer have been in the codebase since §7.6 and
 * nothing called them: `COPY.result.exportMarkdown` existed, unreferenced, and
 * the result screen offered no way to take the story anywhere. These tests are
 * about the wiring, which is the part that was missing.
 */

const buttonNamed = (container: Element, label: string): HTMLButtonElement => {
  const found = [...container.querySelectorAll("button")].find(
    (button) => button.textContent === label,
  );
  if (found === undefined) throw new Error(`no button reads "${label}"`);
  return found as HTMLButtonElement;
};

const mount = () =>
  renderStyled(<App initial={demoState()} transport={demoTransport()} />);

describe("the result screen offers both ways out", () => {
  test("the markdown and print controls are on the story tab", () => {
    const { container } = mount();
    expect(buttonNamed(container, COPY.result.exportMarkdown).disabled).toBe(
      false,
    );
    expect(buttonNamed(container, COPY.result.exportPdf).disabled).toBe(false);
  });

  test("nothing but the story prints", () => {
    // The print stylesheet removes `[data-print="chrome"]` and keeps the rest,
    // so what must be marked is the rail, the tabs and the controls. A control
    // that lost its mark would print as a button on the page, which is the
    // failure nobody sees until a PDF exists.
    const { container } = mount();
    const chrome = [...container.querySelectorAll('[data-print="chrome"]')];
    expect(chrome.length).toBeGreaterThanOrEqual(3);
    expect(
      chrome.some(
        (element) =>
          element.querySelector("nav") !== null || element.tagName === "NAV",
      ),
    ).toBe(true);
    expect(
      buttonNamed(container, COPY.result.exportMarkdown).closest(
        '[data-print="chrome"]',
      ),
    ).not.toBeNull();
  });

  test("the story itself is not marked as chrome", () => {
    // The rule is stated by exclusion, so the way to get a blank PDF is to
    // mark the prose. This is the assertion that would catch it.
    const { container } = mount();
    const prose = [...container.querySelectorAll("p")].find((element) =>
      element.textContent?.includes("The lamp turned through the fog"),
    );
    expect(prose?.closest('[data-print="chrome"]')).toBeNull();
  });
});

describe("the markdown control hands over the exported document", () => {
  const realCreate = URL.createObjectURL;
  const realRevoke = URL.revokeObjectURL;

  afterEach(() => {
    URL.createObjectURL = realCreate;
    URL.revokeObjectURL = realRevoke;
  });

  test("it asks the export route and saves what came back", async () => {
    // The failure this catches: a control wired to the story already in
    // `state.view` rather than to `GET /api/sessions/:id/export`. The two are
    // different documents — the route's carries §7.6's label, the fit report
    // and the decisions log — and the story view would look right while the
    // downloaded file was missing the part the label makes mandatory.
    const bodies: string[] = [];
    URL.createObjectURL = (blob: Blob) => {
      void blob.text().then((text) => bodies.push(text));
      return "blob:recorded";
    };
    URL.revokeObjectURL = () => undefined;

    const { container } = mount();
    await act(async () => {
      buttonNamed(container, COPY.result.exportMarkdown).click();
    });

    expect(bodies).toHaveLength(1);
    expect(bodies[0]).toContain("Generated by auteur in the style of");
  });

  test("a refused export says so instead of failing silently", async () => {
    // A download that produces no file and no message is indistinguishable
    // from a browser that blocked it, and the reader has no next move either
    // way. The alert is the difference.
    const demo = demoTransport();
    const refusing: Transport = {
      ...demo,
      client: {
        call: async (name: string, options?: unknown) => {
          if (name === "exportStory") {
            throw new AuteurError("not_found", "This session has no draft.");
          }
          return demo.client.call(name as never, options as never);
        },
      } as unknown as Transport["client"],
    };

    const { container } = renderStyled(
      <App initial={demoState()} transport={refusing} />,
    );
    expect(container.querySelector('[role="alert"]')).toBeNull();

    await act(async () => {
      buttonNamed(container, COPY.result.exportMarkdown).click();
    });

    expect(container.querySelector('[role="alert"]')?.textContent).toBe(
      COPY.result.exportFailed,
    );
  });
});
