import { describe, expect, test } from "bun:test";
import { COPY } from "@auteur/copy/index";
import { renderStyled } from "@auteur/test-support/render";
import { App } from "../shell/app.tsx";
import { STEP_ORDER } from "../shell/session-state.ts";
import { RECORDED_LOG } from "./recorded-log.ts";
import { demoState, demoTransport } from "./transport.ts";

/**
 * Demo mode as the entry point builds it.
 *
 * The screens' own tests inject `initial` state directly, which is why they
 * passed while the real demo could reach exactly one screen: nothing gave it a
 * session, so `sessionId` was undefined and six of the seven were unreachable.
 * These mount what `main.tsx` mounts.
 */

const mount = () =>
  renderStyled(<App initial={demoState()} transport={demoTransport()} />);

describe("the demo mounts into a session, not an empty app", () => {
  test("it starts at the end, so every screen is reachable backwards", () => {
    // The rail refuses forward navigation — pending steps are not clickable —
    // so a demo starting mid-run shows only the steps behind it. Starting on
    // `idea` with no session at all was the state that made every screen
    // unreachable.
    expect(demoState().view?.session.step).toBe("result");
    const { container } = mount();
    expect(container.textContent).toContain(COPY.shell.steps.result);

    // Every step behind the current one is an enabled rail button; the current
    // one is not, because jumping to where you already are is not a jump.
    // Compared by label, not by element: `toEqual` on a DOM node walks its
    // parent chain and does not come back — which is what hung this test
    // before it ever printed a name.
    const disabled = [
      ...container.querySelectorAll<HTMLButtonElement>("nav button"),
    ]
      .filter((button) => button.disabled)
      .map((button) => button.textContent);
    expect(disabled).toEqual([COPY.shell.steps.result]);
  });

  test("the story renders on the step the demo opens at", () => {
    const { container } = mount();
    expect(container.textContent).toContain("The lamp turned through the fog");
  });

  test("the recorded detail lines render on the research screen", () => {
    // The log exists to be looked at. If it never reaches a screen it is a
    // fixture with one consumer, and that consumer is a test.
    const state = demoState();
    const view = state.view;
    if (view === undefined) throw new Error("the demo has no session");
    const { container } = renderStyled(
      <App
        initial={{
          ...state,
          view: { ...view, session: { ...view.session, step: "research" } },
        }}
        transport={demoTransport()}
      />,
    );
    expect(container.textContent).toContain("38 works found; choosing 12");
  });

  test("the attribution names the author, not an empty string", () => {
    // `Generated by auteur in the style of .` is what a demo with no card
    // renders, and it is the one sentence on the screen that must be right.
    const { container } = mount();
    expect(container.textContent).toContain(
      "in the style of Chekhov, Anton Pavlovich",
    );
  });

  test("every step is reachable through the rail", async () => {
    // Not "every screen renders when handed state" — every screen renders
    // from what the entry point actually provides.
    const transport = demoTransport();
    for (const step of STEP_ORDER) {
      const session = await transport.client.call("patchSession", {
        body: { step },
        params: { id: "x" },
      });
      expect(session.step).toBe(step);
      // Read back the way the app does, so the view is the transport's own
      // rather than one this test assembled from parts.
      const view = await transport.client.call("session", {
        params: { id: "x" },
      });
      const { container } = renderStyled(
        <App initial={{ ...demoState(), view }} transport={transport} />,
      );
      expect(container.querySelector("main")?.textContent ?? "").not.toBe("");
    }
  });
});

describe("the demo answers only what it has recorded", () => {
  test("an unrecorded route throws rather than answering with nothing", async () => {
    // A demo that silently answered `{}` teaches a reader the product does
    // nothing.
    await expect(
      demoTransport().client.call("pins", {
        body: { pins: {} },
        params: { id: "x" },
      }),
    ).rejects.toThrow(/no recorded answer/);
  });

  test("the stream replays from the cursor, like the real one", () => {
    // A demo that reloaded would otherwise deliver the whole log twice.
    const delivered: number[] = [];
    demoTransport().openStream("x", 4, (event) => {
      delivered.push(event.seq);
    });
    expect(delivered).toEqual(
      RECORDED_LOG.filter((event) => event.seq > 4).map((event) => event.seq),
    );
    expect(delivered).not.toContain(1);
  });
});
