import {
  afterAll,
  beforeAll,
  beforeEach,
  describe,
  expect,
  test,
} from "bun:test";
import { ROUTE_NAMES, ROUTES } from "@auteur/api-contract/routes";
import { putCard } from "@auteur/card-store/cards";
import type { StyleCard } from "@auteur/core/style-card";
import { newId } from "@auteur/ids/new-id";
import { putArtifact } from "@auteur/session-store/artifacts";
import { createSession, updateSession } from "@auteur/session-store/sessions";
import { createTestDb, type TestDb } from "@auteur/test-db/test-db";
import { createApp } from "../../server/_app.ts";

const TOKEN = "a-token-of-at-least-16-chars";
const AUTHOR = "gutenberg:chekhov-anton-pavlovich-1860";

let harness: TestDb;
let sessionId: string;
let app: ReturnType<typeof createApp>;

beforeAll(async () => {
  harness = await createTestDb();
  await harness.db.query(
    `INSERT INTO authors (id, provider, kind, display_name, work_count)
     VALUES ($1, 'gutenberg', 'full-text', 'Chekhov, Anton Pavlovich', 12)`,
    [AUTHOR],
  );
});

afterAll(async () => {
  await harness.close();
});

beforeEach(async () => {
  const session = await createSession(harness.db, {
    id: newId(),
    idea: "a lighthouse keeper",
    lengthPreset: "flash",
  });
  sessionId = session.id;
  app = createApp({ apiToken: TOKEN, db: harness.db });
});

const aCard = () =>
  ({
    author: { displayName: "Chekhov, Anton Pavlovich" },
  }) as unknown as StyleCard;

const withCardAndDraft = async (): Promise<number> => {
  const written = await putCard(harness.db, {
    authorId: AUTHOR,
    buildKey: `export-${sessionId}`,
    card: aCard(),
    confidence: 0.86,
    id: newId(),
    provenance: "full-text",
  });
  await updateSession(harness.db, sessionId, {
    authorId: AUTHOR,
    cardId: written.card.id,
  });
  await putArtifact(harness.db, {
    body: {
      markdown: "The lamp turned. The sea did not.",
      title: "Landfall",
      wordCount: 7,
    },
    inputKey: "draft-key",
    kind: "draft",
    sessionId,
  });
  return written.card.version;
};

const get = async (): Promise<Response> =>
  app.request(`/api/sessions/${sessionId}/export`, {
    headers: { authorization: `Bearer ${TOKEN}` },
  });

describe("the export carries the label", () => {
  test("it returns text/markdown containing the §7.6 sentence verbatim", async () => {
    await withCardAndDraft();
    const response = await get();
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("text/markdown");

    const document = await response.text();
    expect(document).toContain(
      "Generated by auteur in the style of Chekhov, Anton Pavlovich.",
    );
    expect(document).toContain("AI-generated text; not written by the author.");
    expect(document).toContain("The lamp turned. The sea did not.");
  });

  test("there is no query parameter that suppresses it", async () => {
    // §7.6 is structural: `renderExport` takes the label as a required
    // argument, so no branch here can produce a document without it. This
    // asserts the route offers no way to ask for one either.
    await withCardAndDraft();
    for (const query of ["?label=false", "?plain=1", "?raw=true"]) {
      const response = await app.request(
        `/api/sessions/${sessionId}/export${query}`,
        { headers: { authorization: `Bearer ${TOKEN}` } },
      );
      expect(await response.text()).toContain("Generated by auteur");
    }
  });

  test("the contract declares no query for this route, so none can be honoured", async () => {
    expect(ROUTE_NAMES).toContain("exportStory");
    expect(ROUTES.exportStory.method).toBe("GET");
    expect("query" in ROUTES.exportStory).toBe(false);
  });

  test("the document carries the card version and confidence", async () => {
    // A reader who did not run the session can tell what was chosen for them.
    // The version is read back rather than written as a literal: cards version
    // per author, and this suite writes several for the same one.
    const version = await withCardAndDraft();
    expect(await (await get()).text()).toContain(
      `card@${version.toString()}, confidence 0.86`,
    );
  });
});

describe("there is nothing to export", () => {
  test("no draft is 404, not an empty document with a label on it", async () => {
    // An export of nothing carrying the attribution sentence would be a file
    // claiming a story was generated in someone's style when none was.
    const response = await get();
    expect(response.status).toBe(404);
  });

  test("a draft but no card is 404", async () => {
    await putArtifact(harness.db, {
      body: { markdown: "The lamp turned.", title: null, wordCount: 3 },
      inputKey: "draft-key",
      kind: "draft",
      sessionId,
    });
    expect((await get()).status).toBe(404);
  });

  test("an unknown session is 404", async () => {
    const response = await app.request(
      "/api/sessions/b1c9f2e0-0000-4000-8000-abcdefabcdef/export",
      { headers: { authorization: `Bearer ${TOKEN}` } },
    );
    expect(response.status).toBe(404);
  });
});
