#!/usr/bin/env bun
import { existsSync } from "node:fs";
/**
 * CI gate 4: the public API surface snapshot.
 *
 * For every package, every subpath in its `exports` map is scanned for the
 * names it exports and the declaration text that introduces each one. The
 * result is written to `packages/<name>/api-surface.md`.
 *
 * `--check` fails when a package's regenerated surface differs from the
 * committed file, so widening (or narrowing) a package's interface cannot land
 * without the snapshot change showing up in the diff and being reviewed.
 *
 * ## Star re-exports are refused outright
 *
 * The names come from `Transpiler.scan(...).exports`, which reports what a file
 * *writes down* and does not resolve `export * from "./other"`. So a star
 * re-export adds every name of its target to the subpath's public surface while
 * this gate reports it unchanged — the named form is caught and the habitual
 * form is not, which is exactly the wrong way round.
 *
 * Rather than resolve the target, the run **fails naming the file**. That is
 * stricter and cheaper, and it matches the flat-subpath discipline
 * `scripts/packages.manifest.ts` enforces everywhere else: a package's contract
 * is the list of subpaths in the manifest and the names each one declares. A
 * star re-export is a contract change written where the manifest cannot see it.
 * Write the names out, or give the target its own subpath.
 *
 * It fails in `--write` mode too. A snapshot generated over a file whose real
 * surface the generator cannot see is a snapshot that certifies the wrong
 * thing, and writing it would launder the problem into the committed tree.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Transpiler } from "bun";
import { PACKAGES } from "./packages.manifest.ts";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");

// One transpiler per loader: a `.ts` file may use a generic arrow
// (`<T>(x) => …`), which the tsx loader parses as JSX and rejects.
const transpilers = {
  ts: new Transpiler({ loader: "ts" }),
  tsx: new Transpiler({ loader: "tsx" }),
};

/**
 * The declaration text for `name`, normalized to a single line. Falls back to
 * the bare name when the declaration cannot be located (a re-export, say),
 * which still catches additions and removals.
 */
const declarationFor = (source: string, name: string): string => {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(
    `^export\\s+(?:declare\\s+)?(?:async\\s+)?(?:const|let|var|function|class|type|interface|enum|abstract\\s+class)\\s+${escaped}\\b[^\\n]*`,
    "m",
  );
  const match = pattern.exec(source);
  if (match === null) {
    return name;
  }
  const line = match[0]
    .replace(/\s*[={]\s*$/, "")
    .replace(/\s+/g, " ")
    .trimEnd();
  return line.replace(/;$/, "");
};

/**
 * Lines of `source` that re-export something without naming it.
 *
 * Anchored at the start of a line so a `//` comment or a jsdoc continuation
 * (` * export * from …`) does not match, and `export type * from` is caught
 * alongside the value form — it widens the type surface just as invisibly.
 */
const starReexports = (source: string): readonly string[] => {
  const found: string[] = [];
  for (const [index, line] of source.split("\n").entries()) {
    if (/^[ \t]*export\s*(?:type\s+)?\*/.test(line)) {
      found.push(`line ${(index + 1).toString()}: ${line.trim()}`);
    }
  }
  return found;
};

/** Every star re-export found, as `file` plus the offending lines. */
const starred: string[] = [];

/**
 * `undefined` when the package is declared in the manifest but nobody has
 * materialized it yet. Those have no `package.json` and no sources, so there
 * is no surface to snapshot — see `docs/IMPLEMENTATION-PLAN.md`'s
 * declared-not-materialized rule.
 */
const surfaceFor = async (packageName: string): Promise<string | undefined> => {
  const dir = join(ROOT, "packages", packageName);
  const manifestFile = Bun.file(join(dir, "package.json"));
  if (!(await manifestFile.exists())) {
    return undefined;
  }
  const manifest = (await manifestFile.json()) as {
    exports?: Record<string, string>;
  };
  const entries = Object.entries(manifest.exports ?? {}).sort(([a], [b]) =>
    a < b ? -1 : 1,
  );

  const lines = [
    `# @auteur/${packageName} — public API surface`,
    "",
    "Generated by `bun run fix:api-surface`. Do not edit by hand.",
    "",
    "Every entry below is reachable by a consumer. A diff here is a contract",
    "change and needs a contract review, per the implementation plan's gate 4.",
    "",
  ];

  for (const [subpath, file] of entries) {
    const path = join(dir, file.replace(/^\.\//, ""));
    lines.push(
      `## \`@auteur/${packageName}${subpath.replace(/^\./, "")}\``,
      "",
    );
    if (!existsSync(path)) {
      lines.push("_source file missing_", "");
      continue;
    }
    // A package may export a data file rather than a module: auteur's two
    // tooling packages export the tsconfig and biome JSON that other packages
    // extend. There is no export surface to scan, and handing JSON to the TS
    // transpiler is a parse error rather than an empty result. The contract is
    // still snapshotted — the subpath's presence is the contract, and its
    // disappearance is the diff.
    if (!/\.[cm]?tsx?$/.test(path)) {
      lines.push("_data file; the subpath itself is the contract_", "");
      continue;
    }

    const source = await Bun.file(path).text();
    for (const line of starReexports(source)) {
      starred.push(
        `packages/${packageName}/${file.replace(/^\.\//, "")} ${line}`,
      );
    }
    const transpiler = path.endsWith(".tsx") ? transpilers.tsx : transpilers.ts;
    // A file bun's transpiler refuses would otherwise abort the whole run with
    // only its own diagnostic, which names an internal `input.tsx` rather than
    // the real path — a gate failing for a reason nobody can see.
    let names: string[];
    try {
      names = [...new Set(transpiler.scan(source).exports)].sort();
    } catch (cause) {
      throw new Error(
        `Could not read the exports of ${file} in @auteur/${packageName}. bun's transpiler rejected it; any diagnostic above names its own input file, not this one.`,
        { cause },
      );
    }
    if (names.length === 0) {
      lines.push("_no exports_", "");
      continue;
    }
    lines.push("```ts");
    for (const name of names) {
      lines.push(declarationFor(source, name));
    }
    lines.push("```", "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

const mode = process.argv.includes("--check") ? "check" : "write";
const drifted: string[] = [];
let covered = 0;

for (const spec of PACKAGES) {
  const next = await surfaceFor(spec.name);
  if (next === undefined) {
    continue;
  }
  covered += 1;
  const target = join(ROOT, "packages", spec.name, "api-surface.md");
  if (mode === "write") {
    await writeFile(target, next);
    continue;
  }
  const current = existsSync(target) ? await Bun.file(target).text() : "";
  if (current !== next) {
    drifted.push(spec.name);
  }
}

if (starred.length > 0) {
  process.stderr.write(
    [
      "",
      "Star re-export in a public subpath:",
      ...starred.map((entry) => `  - ${entry}`),
      "",
      '`export * from "./other"` puts every name of the target into this',
      "subpath's public surface, and bun's transpiler does not resolve it — so",
      "this gate would report the surface unchanged while the contract grew.",
      "Name the exports you mean, or give the target its own subpath in",
      "scripts/packages.manifest.ts, which is where a contract change is",
      "reviewed.",
      "",
    ].join("\n"),
  );
  process.exit(1);
}

if (mode === "check" && drifted.length > 0) {
  process.stderr.write(
    [
      "",
      "API surface drift in:",
      ...drifted.map((name) => `  - @auteur/${name}`),
      "",
      "The public exports of these packages no longer match their committed",
      "api-surface.md. Run `bun run fix:api-surface` and review the diff: if it",
      "widens or narrows a package's contract, that is a contract change and",
      "needs a contract reviewer, not a drive-by amendment.",
      "",
    ].join("\n"),
  );
  process.exit(1);
}

process.stdout.write(
  mode === "write"
    ? `wrote ${covered.toString()} api-surface.md files\n`
    : `api surface ok: ${covered.toString()} materialized packages unchanged\n`,
);
