#!/usr/bin/env bun
/**
 * What the gateway's model list says about the catalogue.
 *
 * `compare()` was written on the first day and **nothing ever called the
 * gateway**, so for the whole life of the project this reported on a catalogue
 * and never on the difference between it and reality. It passed every run
 * against a table in which not one id was one the gateway serves (decision
 * 0028). A comparison with one side missing is not a weak check; it is the
 * shape of a check, and it reads exactly like one that works.
 *
 * It now asks. Three things it can tell us:
 *
 *  - a catalogue row the gateway no longer serves, which is a pin waiting to
 *    fail mid-session;
 *  - a model the gateway serves that the catalogue has never heard of, which
 *    means the generated file is stale;
 *  - **a tier candidate that is in neither**, which is the one that took the
 *    product down: resolution walks the list, finds nothing, and the session
 *    fails at its first model call.
 *
 * With no key it says so and fails. Not checking is not the same as passing.
 */
import { TIER_CANDIDATES } from "../packages/config/src/tiers.ts";
import { CATALOGUE } from "../packages/provider-router/src/models.ts";
import { fetchModels } from "./probe-router-catalogue.ts";

export type Drift = {
  readonly missingFromGateway: readonly string[];
  readonly absentFromCatalogue: readonly string[];
};

/**
 * Tier candidates the gateway does not serve.
 *
 * The list a stage resolves through, checked against what exists. Every entry
 * being absent is what "model_unavailable" looked like from the outside, and
 * this names them instead.
 */
export const unservedCandidates = (
  gatewayIds: readonly string[],
): readonly string[] => {
  const gateway = new Set(gatewayIds);
  return [...new Set(Object.values(TIER_CANDIDATES).flat())].filter(
    (id) => !gateway.has(id),
  );
};

export const compare = (
  catalogueIds: readonly string[],
  gatewayIds: readonly string[],
): Drift => {
  const gateway = new Set(gatewayIds);
  const catalogue = new Set(catalogueIds);
  return {
    absentFromCatalogue: gatewayIds.filter((id) => !catalogue.has(id)),
    missingFromGateway: catalogueIds.filter((id) => !gateway.has(id)),
  };
};

/**
 * What the catalogue and the tier lists say, before anything is asked.
 *
 * Printed on every run, with or without a key, because it is the state a reader
 * needs in front of the drift below to know what the drift means.
 */
const summarise = (): string =>
  [
    `${CATALOGUE.length.toString()} catalogue row(s), generated by ` +
      "`bun run catalogue:models`.",
    `${[...new Set(Object.values(TIER_CANDIDATES).flat())].length.toString()} tier candidate(s) across three tiers.`,
    "",
    "Rows that accept a strict json_schema, which every typed stage needs:",
    ...CATALOGUE.filter((row) => row.structuredOutput).map(
      (row) => `  ${row.id}`,
    ),
    "",
    "Rows that do not, which no typed stage may resolve to:",
    ...CATALOGUE.filter((row) => !row.structuredOutput).map(
      (row) => `  ${row.id}`,
    ),
  ].join("\n");

const report = (drift: Drift, unserved: readonly string[]): string =>
  [
    "",
    ...(drift.missingFromGateway.length === 0
      ? ["ok   every catalogue row is one the gateway serves"]
      : [
          "FAIL the gateway no longer serves:",
          ...drift.missingFromGateway.map((id) => `       ${id}`),
          "     Each is a pin waiting to fail mid-session. Re-run",
          "     `bun run catalogue:models`.",
        ]),
    ...(drift.absentFromCatalogue.length === 0
      ? ["ok   the catalogue knows every model the gateway serves"]
      : [
          "FAIL the gateway serves models this catalogue has not got:",
          ...drift.absentFromCatalogue.map((id) => `       ${id}`),
          "     The generated file is stale. Re-run `bun run catalogue:models`.",
        ]),
    ...(unserved.length === 0
      ? ["ok   every tier candidate is a model that exists"]
      : [
          "FAIL these tier candidates are not served by the gateway:",
          ...unserved.map((id) => `       ${id}`),
          "     A stage whose whole list is unserved resolves to nothing and",
          "     fails at its first model call. Fix packages/config/src/tiers.ts.",
        ]),
  ].join("\n");

if (import.meta.main) {
  process.stdout.write(`${summarise()}\n`);
  const key = Bun.env["RAMP_ROUTER_API_KEY"];
  if (key === undefined || key === "") {
    process.stdout.write(
      "\nFAIL no RAMP_ROUTER_API_KEY, so the gateway was not asked.\n" +
        "     Not checking is not the same as passing.\n",
    );
    process.exit(1);
  }
  const gatewayIds = (await fetchModels(key)).map((model) => model.id);
  const drift = compare(
    CATALOGUE.map((row) => row.id),
    gatewayIds,
  );
  const unserved = unservedCandidates(gatewayIds);
  process.stdout.write(`${report(drift, unserved)}\n`);
  const clean =
    drift.missingFromGateway.length === 0 &&
    drift.absentFromCatalogue.length === 0 &&
    unserved.length === 0;
  process.exit(clean ? 0 : 1);
}
