#!/usr/bin/env bun
/**
 * Generate `docs/DECISIONS.md` from `docs/decisions/`.
 *
 * One decision per file, numbered one past the last. The index is **generated**
 * rather than hand-maintained for a reason that is about merge conflicts rather
 * than tidiness: two branches each adding a decision would otherwise both edit
 * the same list, in the same place, every time. Generated, they conflict only
 * in a file that is regenerated after rebase and never hand-merged.
 *
 * `--check` fails when the committed index differs from what the directory
 * generates, which is gate 1's task set.
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const DIR = join(ROOT, "docs", "decisions");
const INDEX = join(ROOT, "docs", "DECISIONS.md");

export type DecisionEntry = {
  readonly number: number;
  readonly slug: string;
  readonly title: string;
  readonly status: string;
  readonly date: string;
  readonly file: string;
};

/**
 * Read the heading and the status line.
 *
 * Both are required, and a file missing either is an error rather than a row
 * with a blank cell: the index is what a reader scans instead of opening thirty
 * files, and a blank cell makes them open the file anyway.
 */
export const parseDecision = (file: string, source: string): DecisionEntry => {
  const named = /^(\d{4})-(.+)\.md$/.exec(file);
  if (named?.[1] === undefined || named[2] === undefined) {
    throw new Error(
      `${file} is not named NNNN-slug.md, so its place in the index is undefined.`,
    );
  }
  const heading = /^#\s+(\d{4})\s+—\s+(.+)$/m.exec(source);
  if (heading?.[1] === undefined || heading[2] === undefined) {
    throw new Error(
      `${file} has no "# NNNN — Title" heading, so the index cannot name it.`,
    );
  }
  if (heading[1] !== named[1]) {
    throw new Error(
      `${file} is numbered ${named[1]} in its filename and ${heading[1]} in its heading.`,
    );
  }
  const meta = /^\*\*Status:\*\*\s+(\S+)\s+·\s+\*\*Date:\*\*\s+(\S+)/m.exec(
    source,
  );
  if (meta?.[1] === undefined || meta[2] === undefined) {
    throw new Error(
      `${file} has no "**Status:** … · **Date:** …" line. Every decision records whether it still holds.`,
    );
  }
  return {
    date: meta[2],
    file,
    number: Number.parseInt(named[1], 10),
    slug: named[2],
    status: meta[1],
    title: heading[2],
  };
};

export const renderIndex = (entries: readonly DecisionEntry[]): string =>
  [
    "# Decisions",
    "",
    "Generated by `bun run decisions:index`. Do not edit by hand.",
    "",
    "One decision per file under [`decisions/`](decisions). A decision is written",
    "when the architecture is wrong or under-specified and the implementation",
    "diverges from it — recorded rather than argued for in a commit message,",
    "because the next reader needs the reasoning and not the outcome.",
    "",
    "| # | Decision | Status | Date |",
    "|---|---|---|---|",
    ...entries.map(
      (entry) =>
        `| ${entry.number.toString().padStart(4, "0")} | [${entry.title}](decisions/${entry.file}) | ${entry.status} | ${entry.date} |`,
    ),
    "",
  ].join("\n");

export const readAll = async (): Promise<DecisionEntry[]> => {
  const files = (await readdir(DIR))
    .filter((name) => name.endsWith(".md"))
    .sort();
  const entries: DecisionEntry[] = [];
  for (const file of files) {
    entries.push(parseDecision(file, await Bun.file(join(DIR, file)).text()));
  }
  const numbers = entries.map((entry) => entry.number);
  if (new Set(numbers).size !== numbers.length) {
    throw new Error(
      "Two decisions share a number. Number one past the last, and rebase rather than reusing.",
    );
  }
  return entries;
};

if (import.meta.main) {
  const generated = renderIndex(await readAll());
  if (process.argv.includes("--check")) {
    const committed = await Bun.file(INDEX)
      .text()
      .catch(() => "");
    if (committed !== generated) {
      process.stderr.write(
        "docs/DECISIONS.md does not match docs/decisions/.\n" +
          "Run `bun run decisions:index` and commit the result.\n",
      );
      process.exit(1);
    }
    process.stdout.write("decisions index ok\n");
  } else {
    await Bun.write(INDEX, generated);
    process.stdout.write(`wrote docs/DECISIONS.md\n`);
  }
}
