#!/usr/bin/env bun
/**
 * The per-package test runner behind `test:unit` and `test:coverage`.
 *
 * Two things it does that a bare `bun test` cannot:
 *
 *  - A package whose sources are still generator placeholders has nothing to
 *    test, so it is skipped rather than failing on "0 test files". The moment a
 *    work package writes real code the skip stops applying, and the package
 *    must ship tests.
 *  - `coverage` runs the integration tests too and applies the package's line
 *    and function floors from `packages.manifest.ts`, so the floor is measured
 *    against every test that exercises the package, not just the pure ones.
 *
 * Layout convention: unit tests are colocated under `src/`, integration tests
 * live in `tests/integration/`.
 */
import { existsSync } from "node:fs";
import { basename, join } from "node:path";
import { Glob } from "bun";
import { APPS, PACKAGES } from "./packages.manifest.ts";

const PLACEHOLDER_MARKER = "Placeholder generated by `bun run new:package`";

const mode = process.argv[2] === "coverage" ? "coverage" : "unit";
const cwd = process.cwd();
const packageName = basename(cwd);
// Apps run through the same runner as packages. They have the same problem —
// a scaffold with no tests fails on "0 test files" — and the same answer, and
// one runner beats two that agree today. An app has no coverage floor and no
// `workspaceDeps` relevant to the database check, so it takes the defaults.
const spec =
  PACKAGES.find((candidate) => candidate.name === packageName) ??
  APPS.find((candidate) => candidate.name === packageName);

if (spec === undefined) {
  process.stderr.write(
    `${packageName} is not in scripts/packages.manifest.ts\n`,
  );
  process.exit(1);
}

const sourceFiles: string[] = [];
for await (const relative of new Glob("src/**/*.{ts,tsx}").scan({ cwd })) {
  sourceFiles.push(relative);
}

const testFiles = sourceFiles.filter((file) => /\.test\.tsx?$/.test(file));
const implementationFiles = sourceFiles.filter(
  (file) => !/\.test\.tsx?$/.test(file),
);

let live = false;
for (const file of implementationFiles) {
  const source = await Bun.file(join(cwd, file)).text();
  if (!source.includes(PLACEHOLDER_MARKER)) {
    live = true;
    break;
  }
}

if (!live) {
  process.stdout.write(
    `@auteur/${packageName}: scaffold only, no implementation yet — nothing to test\n`,
  );
  process.exit(0);
}

if (testFiles.length === 0) {
  process.stderr.write(
    `@auteur/${packageName} has implementation files but no colocated \`*.test.ts\`.\n` +
      "Every work package ships its tests with its implementation.\n",
  );
  process.exit(1);
}

const integrationDir = join(cwd, "tests", "integration");
const hasIntegration = existsSync(integrationDir);

// Only a package that can actually reach Postgres needs the database. A
// package whose integration tests exercise some other real dependency — the
// Blob store, say — has integration tests but no database, and demanding one
// would make its suite unrunnable for the wrong reason.
const needsDatabase = ["db", "migrations", "test-db"].some(
  (name) => packageName === name || spec.workspaceDeps.includes(name),
);

if (
  mode === "coverage" &&
  hasIntegration &&
  needsDatabase &&
  Bun.env["AUTEUR_TEST_DATABASE_URL"] === undefined
) {
  process.stderr.write(
    `@auteur/${packageName} has integration tests but AUTEUR_TEST_DATABASE_URL is unset.\n` +
      "Integration tests run against a real Postgres; there is no mocked database anywhere in packages/.\n",
  );
  process.exit(1);
}

const args = ["test", "src"];
if (mode === "coverage") {
  args.push("--coverage");
  if (hasIntegration) {
    args.push("tests/integration");
  }
} else {
  // Test *files* across worker processes. nexus measured this as the whole
  // difference between a fast `turbo test` and a slow one, concentrated in its
  // two DOM-heavy packages; auteur has no suites yet, so the setting is
  // inherited on nexus's evidence rather than on its own, and the numbers it
  // is worth are not restated here as though they were measured.
  //
  // `--no-isolate` is not a relaxation. `bun test` runs every file of a package
  // in one process with one module registry; isolating would give each file its
  // own, re-importing happy-dom, React and the component library per file —
  // which nexus measured as *slower* than running them serially. Each worker
  // keeps one registry, exactly as the single process did.
  //
  // Deliberately **not** on the coverage path. Bun does not merge function
  // coverage across workers, so the same package reports a lower function
  // percentage under `--parallel` than serially. The coverage floors are
  // measured from those numbers, so parallelising there would quietly measure
  // the wrong thing.
  args.push("--parallel", "--no-isolate");
}

const result = Bun.spawnSync(["bun", ...args], {
  cwd,
  stderr: "inherit",
  stdout: "inherit",
});
process.exit(result.exitCode ?? 1);
