#!/usr/bin/env bun
/**
 * The per-package test runner behind `test:unit` and `test:coverage`.
 *
 * Two things it does that a bare `bun test` cannot:
 *
 *  - A package whose sources are still generator placeholders has nothing to
 *    test, so it is skipped rather than failing on "0 test files". The moment a
 *    work package writes real code the skip stops applying, and the package
 *    must ship tests.
 *  - It brings up a real Postgres for a package that has integration tests, so
 *    those suites run on CI as well as locally. They are half this
 *    repository's proof — every store's guarantees are guarantees *of*
 *    Postgres — and CI has no database service, because the workflow is
 *    written once and the build session cannot push to it. See
 *    `scripts/test-postgres.ts`.
 *  - `coverage` applies the package's line and function floors from
 *    `packages.manifest.ts`, so the floor is measured against every test that
 *    exercises the package, not just the pure ones.
 *
 * Layout convention: unit tests are colocated under `src/`, integration tests
 * live in `tests/integration/`.
 */
import { existsSync } from "node:fs";
import { basename, join } from "node:path";
import { Glob } from "bun";
import { APPS, PACKAGES } from "./packages.manifest.ts";
import { ensureTestPostgres } from "./test-postgres.ts";

const PLACEHOLDER_MARKER = "Placeholder generated by `bun run new:package`";

const mode = process.argv[2] === "coverage" ? "coverage" : "unit";
const cwd = process.cwd();
const packageName = basename(cwd);
// Apps run through the same runner as packages. They have the same problem —
// a scaffold with no tests fails on "0 test files" — and the same answer, and
// one runner beats two that agree today. An app has no coverage floor and no
// `workspaceDeps` relevant to the database check, so it takes the defaults.
const spec =
  PACKAGES.find((candidate) => candidate.name === packageName) ??
  APPS.find((candidate) => candidate.name === packageName);

if (spec === undefined) {
  process.stderr.write(
    `${packageName} is not in scripts/packages.manifest.ts\n`,
  );
  process.exit(1);
}

/**
 * Where an app's implementation lives.
 *
 * A package keeps everything under `src/`. An app also has `api/`, because
 * that is where the platform looks for a function — and a runner that scanned
 * only `src/` would read a fully-routed app as a scaffold, skip it, and never
 * run one route test.
 */
const sourceRoots =
  APPS.find((candidate) => candidate.name === packageName) === undefined
    ? ["src"]
    : ["src", "api"];

const sourceFiles: string[] = [];
for (const root of sourceRoots) {
  for await (const relative of new Glob(`${root}/**/*.{ts,tsx}`).scan({
    cwd,
  })) {
    sourceFiles.push(relative);
  }
}

const testFiles = sourceFiles.filter((file) => /\.test\.tsx?$/.test(file));
const implementationFiles = sourceFiles.filter(
  (file) => !/\.test\.tsx?$/.test(file),
);

let live = false;
for (const file of implementationFiles) {
  const source = await Bun.file(join(cwd, file)).text();
  if (!source.includes(PLACEHOLDER_MARKER)) {
    live = true;
    break;
  }
}

if (!live) {
  process.stdout.write(
    `@auteur/${packageName}: scaffold only, no implementation yet — nothing to test\n`,
  );
  process.exit(0);
}

const integrationDir = join(cwd, "tests", "integration");
const hasIntegration = existsSync(integrationDir);

// Colocated *or* integration. A package whose whole surface is a database
// contract — `migrations`, the stores — has nothing meaningful to assert in a
// pure test, and demanding one would only produce a test that asserts a
// constant.
if (testFiles.length === 0 && !hasIntegration) {
  process.stderr.write(
    `@auteur/${packageName} has implementation files but no tests.\n` +
      "Every work package ships its tests with its implementation: colocated\n" +
      "`*.test.ts` beside the source, or a suite under `tests/integration/`.\n",
  );
  process.exit(1);
}

/**
 * Whether this package can actually reach Postgres.
 *
 * **Transitive, and through devDependencies too.** The first version read only
 * `workspaceDeps` and only for a direct edge, which missed both of the ways a
 * package actually gets there: `corpus-gutenberg` reaches the database through
 * `corpus-store`, and every suite that uses the harness reaches it through
 * `test-db` — a devDependency by construction, since layering forbids a runtime
 * edge to a test package.
 *
 * That was not a theoretical gap. It shipped, and CI caught it as
 * ECONNREFUSED: the suite ran with no server because nothing had started one,
 * while the same run passed locally on a cluster that happened to be up.
 *
 * A package with integration tests that exercise some other real dependency
 * still gets no database, which is right — demanding one would make its suite
 * unrunnable for the wrong reason.
 */
const reachesDatabase = (name: string, seen = new Set<string>()): boolean => {
  if (["db", "migrations", "test-db"].includes(name)) return true;
  if (seen.has(name)) return false;
  seen.add(name);
  const found = PACKAGES.find((candidate) => candidate.name === name);
  if (found === undefined) return false;
  return [...found.workspaceDeps, ...(found.workspaceDevDeps ?? [])].some(
    (dependency) => reachesDatabase(dependency, seen),
  );
};

const needsDatabase = [
  packageName,
  ...spec.workspaceDeps,
  ...(spec.workspaceDevDeps ?? []),
].some((name) => reachesDatabase(name));

// A package with integration tests gets a real server, started here if one is
// not already configured. Not having one is a failure and never a skip: a
// suite that silently does not run is worse than no suite, because the gate
// still reports green.
let databaseUrl: string | undefined;
if (hasIntegration && needsDatabase) {
  databaseUrl = await ensureTestPostgres();
  if (databaseUrl === undefined) {
    process.stderr.write(
      `@auteur/${packageName} has integration tests and no PostgreSQL server is available.\n` +
        "They run against a real Postgres; there is no mocked database anywhere in packages/.\n" +
        "Install a server, or set AUTEUR_TEST_DATABASE_URL to one.\n",
    );
    process.exit(1);
  }
}

const args = [
  "test",
  ...sourceRoots.filter((root) => existsSync(join(cwd, root))),
];
if (hasIntegration) {
  args.push("tests/integration");
}
if (mode === "coverage") {
  args.push("--coverage");
} else {
  // Test *files* across worker processes. nexus measured this as the whole
  // difference between a fast `turbo test` and a slow one, concentrated in its
  // two DOM-heavy packages; auteur has no suites yet, so the setting is
  // inherited on nexus's evidence rather than on its own, and the numbers it
  // is worth are not restated here as though they were measured.
  //
  // `--no-isolate` is not a relaxation. `bun test` runs every file of a package
  // in one process with one module registry; isolating would give each file its
  // own, re-importing happy-dom, React and the component library per file —
  // which nexus measured as *slower* than running them serially. Each worker
  // keeps one registry, exactly as the single process did.
  //
  // Deliberately **not** on the coverage path. Bun does not merge function
  // coverage across workers, so the same package reports a lower function
  // percentage under `--parallel` than serially. The coverage floors are
  // measured from those numbers, so parallelising there would quietly measure
  // the wrong thing.
  args.push("--parallel", "--no-isolate");
}

const result = Bun.spawnSync(["bun", ...args], {
  cwd,
  env:
    databaseUrl === undefined
      ? process.env
      : { ...process.env, AUTEUR_TEST_DATABASE_URL: databaseUrl },
  stderr: "inherit",
  stdout: "inherit",
});
process.exit(result.exitCode ?? 1);
