#!/usr/bin/env bun
/**
 * `bun run catalogue:models` — **[net]** regenerate the model catalogue from
 * the gateway.
 *
 * `packages/provider-router/src/models.ts` was written from documentation and
 * every row was tagged `declared`, with a test asserting no row had ever been
 * measured. The first real model call answered 404: not one id in the table was
 * one the gateway serves. Decision 0028 has the whole of it.
 *
 * The premise that made that possible — "the models route carries no context
 * window, no max output, no structured-output support and no price" — is not
 * true of this gateway. Every entry carries limits, capabilities and prices, so
 * the catalogue is generated from the answer rather than typed from a claim,
 * and `source` is `measured` because it was.
 *
 * It runs from anywhere with a key, writes `src/generated/catalogue.ts`, and
 * the file is committed: the deployment never depends on a live call, and a
 * refresh is a diff somebody reads.
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  type GatewayModel,
  parseGatewayModels,
  toCatalogueRows,
} from "../packages/provider-router/src/gateway-models.ts";
import type { CatalogueRow } from "../packages/provider-router/src/models.ts";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
export const GENERATED = join(
  ROOT,
  "packages/provider-router/src/generated/catalogue.ts",
);

export const MODELS_URL = "https://api.router.com/v1/models";

/** Injected so a test runs offline against a recorded answer. */
export type Fetch = (
  url: string,
  init?: { readonly headers?: Readonly<Record<string, string>> },
) => Promise<Response>;

export const fetchModels = async (
  apiKey: string,
  config: { readonly fetch?: Fetch; readonly url?: string } = {},
): Promise<GatewayModel[]> => {
  const call = config.fetch ?? fetch;
  const response = await call(config.url ?? MODELS_URL, {
    headers: { accept: "application/json", authorization: `Bearer ${apiKey}` },
  });
  if (!response.ok) {
    throw new Error(
      `The gateway answered ${response.status.toString()} for its model list.`,
    );
  }
  return parseGatewayModels(await response.json());
};

const number = (value: number): string =>
  value.toLocaleString("en-US").replaceAll(",", "_");

const rowSource = (row: CatalogueRow): string =>
  [
    "  {",
    `    contextWindow: ${number(row.contextWindow)},`,
    `    creator: ${JSON.stringify(row.creator)},`,
    ...(row.default === true ? ["    default: true,"] : []),
    `    displayName: ${JSON.stringify(row.displayName)},`,
    `    id: ${JSON.stringify(row.id)},`,
    `    maxOutputTokens: ${number(row.maxOutputTokens)},`,
    "    pricing: {",
    `      inputPerMillion: ${number(row.pricing.inputPerMillion)},`,
    `      outputPerMillion: ${number(row.pricing.outputPerMillion)},`,
    "    },",
    `    source: "measured",`,
    `    structuredOutput: ${row.structuredOutput.toString()},`,
    "  },",
  ].join("\n");

/**
 * The generated module, as text.
 *
 * Exported so a test can assert the shape without writing to disk, and so the
 * header says in the file itself what regenerates it — a generated file whose
 * first line does not say so is one somebody edits by hand.
 */
export const catalogueSource = (rows: readonly CatalogueRow[]): string =>
  [
    "// Generated by `bun run catalogue:models`. Do not edit.",
    "//",
    "// Every column here is the gateway's own answer, which is why `source` is",
    "// `measured` — see docs/decisions/0028-the-catalogue-comes-from-the-gateway.md.",
    "// Prices are USD micros per million tokens: 1_400_000 is $1.40 per million.",
    "",
    'import type { CatalogueRow } from "../models.ts";',
    "",
    "export const GENERATED_CATALOGUE: readonly CatalogueRow[] = [",
    ...rows.map(rowSource),
    "];",
    "",
  ].join("\n");

if (import.meta.main) {
  const apiKey = Bun.env["RAMP_ROUTER_API_KEY"];
  if (apiKey === undefined || apiKey === "") {
    process.stdout.write(
      "RAMP_ROUTER_API_KEY is unset, so the gateway was not asked and nothing\n" +
        "was written. The catalogue on disk is whatever the last run produced.\n",
    );
    process.exit(1);
  }
  const models = await fetchModels(apiKey);
  const rows = toCatalogueRows(models);
  await writeFile(GENERATED, catalogueSource(rows), "utf8");
  const dropped = models.length - rows.length;
  process.stdout.write(
    `${rows.length.toString()} model(s) written to src/generated/catalogue.ts` +
      `${dropped > 0 ? `, ${dropped.toString()} deprecated one(s) dropped` : ""}.\n` +
      "Run `bun run fix:lint` and commit the diff.\n",
  );
}
