import { describe, expect, test } from "bun:test";
import { ROUTE_NAMES } from "@auteur/api-contract/routes";
import { createClient, withQuery } from "./client.ts";

const jsonResponse = (payload: unknown, status = 200): Response =>
  new Response(JSON.stringify(payload), {
    headers: { "content-type": "application/json" },
    status,
  });

type Recorded = { url: string; init: RequestInit | undefined };

const recording = (
  respond: (url: string) => Response,
): { client: ReturnType<typeof createClient>; calls: Recorded[] } => {
  const calls: Recorded[] = [];
  return {
    calls,
    client: createClient({
      baseUrl: "https://auteur.test",
      fetch: (input, init) => {
        calls.push({ init, url: String(input) });
        return Promise.resolve(respond(String(input)));
      },
    }),
  };
};

const SESSION = {
  authorId: null,
  cardId: null,
  constraints: null,
  createdAt: new Date().toISOString(),
  id: "b1c9f2e0-0000-7000-8000-abcdefabcdef",
  idea: "a lighthouse keeper",
  lengthPreset: "flash",
  step: "idea",
  updatedAt: new Date().toISOString(),
};

describe("one call, generated from the contract", () => {
  test("a route removed from the contract removes it from the client", () => {
    // The type-level property, asserted where it can be: `RouteName` is the
    // contract's keys, so a call naming something else does not compile.
    // @ts-expect-error there is no such route
    const missing = () => createClient().call("noSuchRoute");
    expect(typeof missing).toBe("function");
    expect(ROUTE_NAMES).toContain("health");
  });

  test("the method and the path come from the contract", async () => {
    const { calls, client } = recording(() => jsonResponse({ ok: true }));
    await client.call("health");
    expect(calls[0]?.url).toBe("https://auteur.test/api/health");
    expect(calls[0]?.init?.method).toBe("GET");
  });

  test("a param is filled from options", async () => {
    const { calls, client } = recording(() => jsonResponse(SESSION));
    await client.call("patchSession", {
      body: { step: "author" },
      params: { id: SESSION.id },
    });
    expect(calls[0]?.url).toContain(`/api/sessions/${SESSION.id}`);
    expect(calls[0]?.init?.method).toBe("PATCH");
  });

  test("a query is appended", async () => {
    const { calls, client } = recording(() =>
      jsonResponse({ results: [], unavailable: [] }),
    );
    await client.call("authors", { query: { q: "borges" } });
    expect(calls[0]?.url).toContain("q=borges");
  });
});

describe("the body is parsed before it is sent", () => {
  test("an invalid body throws here rather than becoming a 400", async () => {
    // A client that sent an invalid body and let the server reject it turns a
    // bug in this file into a 400 the user sees, and the stack that produced
    // it is gone by then.
    const { calls, client } = recording(() => jsonResponse(SESSION));
    await expect(
      client.call("createSession", {
        // @ts-expect-error the preset is not one of the four
        body: { idea: "x", lengthPreset: "epic" },
      }),
    ).rejects.toThrow("not valid");
    expect(calls).toEqual([]);
  });

  test("a valid body is sent as JSON", async () => {
    const { calls, client } = recording(() => jsonResponse(SESSION));
    await client.call("createSession", {
      body: { idea: "a lighthouse keeper", lengthPreset: "flash" },
    });
    expect(calls[0]?.init?.headers).toEqual({
      "content-type": "application/json",
    });
    expect(JSON.parse(String(calls[0]?.init?.body))).toEqual({
      idea: "a lighthouse keeper",
      lengthPreset: "flash",
    });
  });
});

describe("the response is parsed, never cast", () => {
  test("a shape the contract does not describe is an error, not undefined", async () => {
    // A client that cast would turn a server-side shape change into
    // `undefined` somewhere in a component, three renders from the request
    // that caused it.
    const { client } = recording(() => jsonResponse({ ok: "yes" }));
    await expect(client.call("health")).rejects.toThrow("cannot read");
  });

  test("a valid response comes back typed", async () => {
    const { client } = recording(() => jsonResponse({ ok: true }));
    expect(await client.call("health")).toEqual({ ok: true });
  });

  test("the export route is read as text, not as JSON", async () => {
    // Its response schema is a string, because the label is inside it and no
    // shape this contract could describe would make that checkable.
    const { client } = recording(
      () =>
        new Response("# A story\n\nGenerated by auteur…", {
          headers: { "content-type": "text/markdown" },
          status: 200,
        }),
    );
    expect(
      await client.call("exportStory", { params: { id: SESSION.id } }),
    ).toContain("Generated by auteur");
  });
});

describe("the server's taxonomy travels", () => {
  test("a coded error keeps its code", async () => {
    // A rate_limited reaching the browser as a generic failure would make the
    // one thing the UI can act on — wait and retry — indistinguishable from
    // the one it cannot.
    const { client } = recording(() =>
      jsonResponse(
        { error: { code: "rate_limited", message: "Slow down." } },
        429,
      ),
    );
    await expect(client.call("health")).rejects.toMatchObject({
      code: "rate_limited",
      message: "Slow down.",
    });
  });

  test("an unrecognised code becomes internal rather than being trusted", async () => {
    // A code the client does not know is one it has no branch for anyway.
    const { client } = recording(() =>
      jsonResponse({ error: { code: "teapot", message: "No." } }, 418),
    );
    await expect(client.call("health")).rejects.toMatchObject({
      code: "internal",
    });
  });

  test("an unreadable error body is internal, not a crash", async () => {
    const { client } = recording(
      () => new Response("<html>502</html>", { status: 502 }),
    );
    await expect(client.call("health")).rejects.toMatchObject({
      code: "internal",
    });
  });
});

describe("a same-origin base is a base", () => {
  test("an empty base produces a relative target, not a throw", async () => {
    // The deployment serves the client and the routes from one origin, so the
    // base is "". `new URL(path, "")` throws — every call from the browser
    // failed before reaching the network, and the button did nothing.
    const seen: string[] = [];
    const client = createClient({
      baseUrl: "",
      fetch: async (url) => {
        seen.push(String(url));
        return new Response(JSON.stringify({ ok: true }), {
          headers: { "content-type": "application/json" },
        });
      },
    });

    await client.call("health");
    expect(seen).toEqual(["/api/health"]);
  });

  test("a configured base is prefixed, and the query survives either way", () => {
    expect(withQuery("/api/authors", { q: "chekhov" })).toBe(
      "/api/authors?q=chekhov",
    );
    expect(
      withQuery("https://preview.auteur.test/api/authors", { q: "a b" }),
    ).toBe("https://preview.auteur.test/api/authors?q=a+b");
    expect(withQuery("/api/health", {})).toBe("/api/health");
  });
});
