const { Button, Icon, Badge, Card, Markdown, ProsodyStat, ProvenanceMark } = window.AuteurDesignSystem_11e1bd;

function ResultStep({ onBack, onRestart }) {
  const D = window.AUTEUR_DATA;
  const [tab, setTab] = React.useState('story');
  return (
    <>
      <StepHeader index={7} title="A Review of the Eddystone Log" blurb="In the style of Jorge Luis Borges. AI-generated; not written by the author."
        aside={
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
            <Button variant="secondary" size="sm"><Icon name="download" size={14} />Export .md</Button>
            <Button variant="ghost" size="sm" onClick={onRestart}>New story</Button>
          </div>
        } />
      <div style={{ display: 'flex', gap: 'var(--space-1)', padding: '0 var(--gutter-screen)', borderBottom: '1px solid var(--border-hairline)' }}>
        {[['story', 'Story'], ['fit', 'Style fit'], ['decisions', 'Decisions log']].map(([k, l]) => (
          <button key={k} onClick={() => setTab(k)} style={{
            background: 'none', border: 'none', borderBottom: `2px solid ${tab === k ? 'var(--accent)' : 'transparent'}`,
            padding: 'var(--space-3) var(--space-4)', font: 'var(--type-label)', cursor: 'pointer',
            color: tab === k ? 'var(--text-strong)' : 'var(--text-faint)', transition: 'var(--transition-control)',
          }}>{l}</button>
        ))}
      </div>
      <StepBody style={{ background: tab === 'story' ? 'var(--surface-panel)' : 'var(--surface-app)' }}>
        {tab === 'story' ? (
          <Card ground="paper" padding="lg" style={{ padding: '56px 64px', maxWidth: 760, margin: '0 auto' }}>
            <Markdown ground="paper">{D.draft}</Markdown>
            <div style={{ marginTop: 'var(--space-10)', paddingTop: 'var(--space-3)', borderTop: '1px solid var(--border-paper)', font: 'var(--type-caption)', color: 'var(--text-paper-faint)' }}>
              Generated by auteur in the style of Jorge Luis Borges. AI-generated text; not written by the author.
            </div>
          </Card>
        ) : null}
        {tab === 'fit' ? (
          <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 320px', gap: 'var(--space-10)', alignItems: 'start' }}>
            <div>
              <SectionLabel action={<Badge tone="edited">1 drift</Badge>}>Findings — critique stage</SectionLabel>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
                {D.findings.map((f, i) => (
                  <Card key={i} ground="ink" padding="md" accent={f.status === 'pass' ? 'var(--status-pass)' : 'var(--status-drift)'}
                    style={{ display: 'flex', gap: 'var(--space-3)' }}>
                    <span style={{ color: f.status === 'pass' ? 'var(--status-pass)' : 'var(--status-drift)', flex: '0 0 auto', marginTop: 2 }}>
                      <Icon name={f.status === 'pass' ? 'check' : 'trending-up'} size={15} />
                    </span>
                    <p style={{ font: 'var(--type-body)', color: 'var(--text-body)', lineHeight: 'var(--leading-normal)', maxWidth: 'var(--measure-prose)' }}>{f.text}</p>
                  </Card>
                ))}
              </div>
              <div style={{ marginTop: 'var(--space-5)', display: 'flex', gap: 'var(--space-2)' }}>
                <Button variant="primary">Run targeted revision</Button>
                <Button variant="ghost">Regenerate beat 3</Button>
              </div>
            </div>
            <aside>
              <SectionLabel>Draft vs corpus band</SectionLabel>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
                {D.fit.map((p) => <ProsodyStat key={p.label} {...p} />)}
              </div>
              <div style={{ marginTop: 'var(--space-4)', display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                <ProvenanceMark origin="measured" source="corpus, 412,118 words" />
                <span style={{ font: 'var(--type-caption)', color: 'var(--text-faint)', lineHeight: 'var(--leading-normal)' }}>
                  Hairline = prosodyTarget. Marker = the draft. Edited targets are scored separately and never reported as the author's statistics.
                </span>
              </div>
            </aside>
          </div>
        ) : null}
        {tab === 'decisions' ? (
          <div style={{ maxWidth: 720 }}>
            <SectionLabel>Every choice the model made for you</SectionLabel>
            {D.decisions.map(([k, v, how]) => (
              <div key={k} style={{ display: 'grid', gridTemplateColumns: '150px minmax(0,1fr) 200px', gap: 'var(--space-4)', padding: 'var(--space-3) 0', borderBottom: '1px solid var(--border-hairline)', alignItems: 'baseline' }}>
                <span style={{ font: 'var(--type-data)', fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>{k}</span>
                <span style={{ font: 'var(--type-body)', color: 'var(--text-body)' }}>{v}</span>
                <span style={{ font: 'var(--type-caption)', color: how === 'answered' ? 'var(--text-muted)' : 'var(--edited)', textAlign: 'right' }}>{how}</span>
              </div>
            ))}
          </div>
        ) : null}
      </StepBody>
      <StepFooter back="Draft" onBack={onBack}>
        <Button variant="secondary">Restart from step 4</Button>
        <Button variant="primary" size="lg"><Icon name="download" size={14} />Export markdown</Button>
      </StepFooter>
    </>
  );
}

Object.assign(window, { ResultStep });
